name: 'Test Action'
description: 'Getting configmap info from consul to Helm'
runs:
  using: 'composite'
  steps:
      - run: bash ${{ github.action_path }}/run.sh
        shell: bash
        env:
          INPUT_CONSULURL: keyvalue
          AKS_SECRET: ${{ secrets.AKS_SECRET }}
      - id: executing_shell
        run: bash ${{ github.action_path }}/runshell.sh
        shell: bash



